apiVersion: apps/v2
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLables:
      app: my-app
  template:
    metadata:
      lables:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx
